#ifndef ROM_BOT_H
#define ROM_BOT_H
//#include <Arduino.h> 
#include <math.h>
//! A class for the parameters of a RP rehabilitation robot
/*!
   This class contains all the necessary parameters for running control algorithms for an at home
   rehabilitation robot. The primary parameters include the states of all joints and the End-Effector (EE) as well as numerous
   dynamic paramters. 
*/
class RomBot { 

    public:

        /**
        * @brief Constructor for RomBot Class
        * @param[in] revoluteLength Length of revolute link
        * @param[in] mass Array of doubles that contain masses for the two links and handle (size = numBodies_) 
        * @param[in] inertia Array of doubles that contain the inertial terms for the two links and handle (size = numBodies_) 
        */
        RomBot(double revoluteLength, double mass[], double inertia[]); 
        


        /**
        * @brief Function to update parameter values from sensor mesurements
        * @param[in] thetaSensed Position of revolute joint read from encoder
        * @param[in] dSensed Postion of prismatic joint read from encoder 
        * @param[in] thetadotSensed Velocity of revolute joint read from encoder and sampled over time
        * @param[in] rdotSensed Velocity of prismatic joint read from encoder and sampled over time
        * @param[in] extFSensed Force at the EE read from a force sensor  
        */
        void updateRomBot(double thetaSensed, double rSensed,double thetadotSensed, double rdotSensed, double extFSensed); 
        
        
        void updateRomBot(double thetaSensed, double rSensed, double extFSensed); 


        
        /**
        * @brief Forward dynamics that takes the updated q,qdot, and tau and maps to qddot to update observed accelerations in joint and task space for RomBot obj  
        * @param[in] tau 2D array containing current torque commands at the joint generated by controller 
        */
        void forwardDyanmics(double tau[]); 

        /**
        * @brief Getter for length of revolute linkage  
        * @return Length as const double 
        */
        const double getRevoluteLength(); 


        /**
        * @brief Getter for mass array of size numBodies_ 
        * @return Const double pointer to first element in array 
        */
        const double *getMass() const; 

        /**
        * @brief Getter for inertia array of size numBodies_  
        * @return Const double pointer to first element in array 
        */
        const double *getInertia() const; 

        /**
        * @brief Getter for revolute position
        * @return theta taken directly from q_[0]
        */
        double getTheta(); 

        /**
        * @brief Getter for prismatic position 
        * @return theta taken directly from q_[1]
        */
        double getR(); 

        
        /**
        * @brief Getter for externalForce position 
        * @return Current externalForce_ read from force sensor 
        */
        double getExternalForce(); 

        /**
        * @brief Getter for revolute velocity of 
        * @return thetaDot taken directly from qdot_[0]
        */
        double getThetaDot(); 

        /**
        * @brief Getter for prismatic velocity  
        * @return thetaDot taken directly from qdot_[1]
        */
        double getRDot(); 

        /**
        * @brief Getter for postion of the EE (x)  
        * @return double pointer to first element in array
        */
        double *getPosEE(); 
        
        /**
        * @brief Getter for velocity of the EE (xdot)  
        * @return double pointer to first element in array
        */
        double *getVelEE(); 

        /**
        * @brief Getter for acceleration of the EE (xddot)  
        * @return double pointer to first element in array
        */
        double *getAccEE(); 



    private:

        /**
        * @brief Forward kinematics that takes the updated q and maps to x
        */
        void forwardKinematics(); 

        /**
        * @brief Differential Kinematics that take the updated qdot and maps to xdot
        */
        void differentialKinematics(); 

        /// Number of Rigid bodies in dynamical System 
        static const int numBodies_ = 3; 

        /// Size of work/operation space (for our use case we are in the plane but if we were in 3D we would choose 6)
        static const int workspaceSize_ = 3; 

        /// Number of Degrees-Of-Freedom 
        static const int DOF_ = 2;

        /// Length of revolute joint  
        double revoluteLength_;

        /// Mass array 
        double mass_[numBodies_];

        /// Inertia Array 
        double inertia_[numBodies_];   
        
        /// Position array [theta , r]         
        double q_[DOF_]; 

        /// Velocity array [thetadot, rdot]
        double qdot_[DOF_]; 

        /// Acceleration array [thetaddot, rddot]
        double qddot_[DOF_]; 

        /// Postion of EE [x,y,theta] 
        double x_[workspaceSize_];

        /// Velocity of EE [xdot,ydot,thetadot] 
        double xdot_[workspaceSize_]; 

        /// Acceleration of EE [xddot,yddot,thetaddot] 
        double xddot_[workspaceSize_]; 

        /// External Force at the EE
        double externalForce_ = 0; 
        
};
#endif // ROM_BOT_H 